### ISSUE TITLE
how config pagenate ? userEntity, for repository ? 

### ISSUE THREAD

**Issue by khanhnam99** [pietrzakadrian/nestjs-typeorm-pagination#1]
{
  "data": [
    {
      "firstName": "Adrian",
      "lastName": "Pietrzak",
      "images":[
            {
              "id": 1,
               "name": "Love",
               "url": "https://cms.hi.com/uploads/Facebook_Logo_504728a787.jpg",
             },
             {
			  "id": 2,
			   "name": "Love cha",
			   "url": "https://cms.hi.com/uploads/Facebook_Logo_504728a787.jpg",
              }
          ]
    },
	{
      "firstName": "Adrian demo",
      "lastName": "Pietrzak demo",
      "images":[
            {
              "id": 1,
               "name": "Love demo",
               "url": "https://cms.hi.com/uploads/Facebook_Logo_504728a787.jpg",
             },
             {
			  "id": 2,
			   "name": "Love cha demo",
			   "url": "https://cms.hi.com/uploads/Facebook_Logo_504728a787.jpg",
              }
          ]
    },
  ],
  "meta": {
    "page": 1,
    "take": 4,
    "itemCount": 12,
    "pageCount": 3,
    "hasPreviousPage": false,
    "hasNextPage": true
  }
}

**Comment by khanhnam99** [comment]
![image](https://user-images.githubusercontent.com/575720/150940178-a926fc08-6bf2-405f-a518-421402996e00.png)

**Comment by pietrzakadrian** [comment]
I don't really understand your question. Please rephrase it so that it is understandable.
